CC = clang
CFLAGS = -Weverything

all: 1-1 1-2 1-3 1-4 1-5

1-1: 1-1.c
	$(CC) -o 1-1.out 1-1.c $(CFLAGS)

1-2: 1-2.c
	$(CC) -o 1-2.out 1-2.c $(CFLAGS)

1-3: 1-3.c
	$(CC) -o 1-3.out 1-3.c $(CFLAGS)

1-4: 1-4.c
	$(CC) -o 1-4.out 1-4.c $(CFLAGS)

1-5: 1-5.c
	$(CC) -o 1-5.out 1-5.c $(CFLAGS)
